#!/bin/bash

_algocopier_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd -P)/.."

if [[ $1 = "config" ]]; then
  $EDITOR "$_algocopier_path/config.yml"
  exit 0
fi

ruby "$_algocopier_path/lib/main.rb" "$@"

unset _algocopier_path
