name: Keep Alive

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: tools/keepalive

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@2.0.10
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.2.0
          cache: yarn
          cache-dependency-path: tools/keepalive/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run keepalive script
        run: yarn start
        env:
          ALGOLIA_APP_IDS: ${{ secrets.ALGOLIA_APP_IDS }}
          ALGOLIA_API_KEYS: ${{ secrets.ALGOLIA_API_KEYS }}
          ALGOLIA_KEEPALIVE_INDEX: ${{ secrets.ALGOLIA_KEEPALIVE_INDEX }}
